# @name user
POST https://todolist-rocket-z74s.onrender.com/users/
Content-Type: application/json

{
  "name": "Vinícius Lima",
  "username": "vlimass",
  "password": "12345"
}

###

# @name task
POST https://todolist-rocket-z74s.onrender.com/tasks/
Content-Type: application/json
Authorization: Basic vlimass 12345

{
  "description": "Terminar o trabalho o mais rápido possível",
  "title": "Trabalho do Paixão",
  "priority": "ALTA",
  "startAt": "2023-10-21T11:00:00",
  "endAt": "2023-10-21T12:00:00" 
}

###

GET https://todolist-rocket-z74s.onrender.com/tasks/
Content-Type: application/json
Authorization: Basic vlimass 12345

###

PUT https://todolist-rocket-z74s.onrender.com/tasks/2e18250b-71c4-41f8-a897-60dec4204500
Content-Type: application/json
Authorization: Basic vlimass 12345

{
  "description": "Mudei a descrição",
  "title": "Mudei o título"
}