# @name user
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "Vinícius Lima",
  "username": "vlimass",
  "password": "12345"
}

###

# @name task
POST http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic vlimass 12345

{
  "description": "Terminar o trabalho o mais rápido possível",
  "title": "Trabalho do Paixão",
  "priority": "ALTA",
  "startAt": "2023-10-21T11:00:00",
  "endAt": "2023-10-21T12:00:00" 
}

###

GET http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic vlimass 12345

###

PUT http://localhost:8080/tasks/98a39c2a-0bd3-46f2-8504-2c386985e5a9
Content-Type: application/json
Authorization: Basic vlimass 12345

{
  "description": "Mudei a descrição",
  "title": "Mudei o título"
}